Repository Diaga/Distributed-Finder, pull requests merged in 2020-12, with the labels that each got.

#45 :feat: Implement cat, cat-at with -w tag, fmap command
  base/terminal.py
  commands/cat.py
  commands/cat_at.py
  commands/fmap.py
  commands/pwd.py
  db/base.py
  db/dao/file_dao.py
  db/dao/sector_dao.py
  db/models/sector.py
  main.py
Labels: enhancement

#47 docs(docs): add user guide and sphinx documentation
  commands/cat.py
  docs/Makefile
  docs/make.bat
  docs/source/autodocs/base.rst
  docs/source/autodocs/commands.rst
  docs/source/autodocs/db.dao.rst
  docs/source/autodocs/db.models.rst
  docs/source/autodocs/db.rst
  docs/source/autodocs/main.rst
  docs/source/autodocs/modules.rst
  docs/source/commands.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/user_guide.rst
  requirements.txt
Labels: documentation

#50 fix(error): catch memory error
  base/terminal.py
Labels: bug

#53 feat(initial refactoring for lab 10): allows changing stdout and runn…
  base/arguments.py
  base/command.py
  base/terminal.py
  commands/cat.py
  commands/cat_at.py
  commands/cat_end.py
  commands/fmap.py
  commands/kthreads.py
  commands/ls.py
  db/db.py
  docs/source/conf.py
  main.py
Labels: enhancement
